## https://www.appveyor.com/docs/appveyor-yml/

image: Visual Studio 2019

version: 1.1.{build}

configuration:
- Debug

platform: Any CPU

pull_requests:  
  do_not_increment_build_number: true

environment:
  # Don't report back to the mothership
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  JAVA_HOME: C:\Program Files\Java\jdk15

init:
- ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

before_build:
- appveyor-retry dotnet restore src -v Minimal
- set DNX_BUILD_VERSION=%APPVEYOR_BUILD_NUMBER%
- dotnet --info

build:
  publish_nuget: true
  publish_nuget_symbols: true
  use_snupkg_format: true 
  include_nuget_references: true
  verbosity: minimal

build_script:
- dotnet tool install --global dotnet-sonarscanner --version 5.0.4
- dotnet sonarscanner begin /o:"cortside" /k:"cortside_cortside.restsharpclient" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="33b175754cf174e1df1b0a7780682a0eea0715c6" /d:sonar.cs.opencover.reportsPaths="**/coverage.opencover.xml"
- dotnet build src --configuration %Configuration% /property:Version=%APPVEYOR_BUILD_VERSION%
- dotnet test src /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
- dotnet sonarscanner end /d:sonar.login="33b175754cf174e1df1b0a7780682a0eea0715c6"

after_build:
- ps: >-
    $branch = $ENV:APPVEYOR_REPO_BRANCH;
    $fileVersion = $env:APPVEYOR_BUILD_VERSION;
    if($branch -ne 'master') {
        $fileVersion = "${fileVersion}-${branch}"; 
    }   
    dotnet pack src/cortside.restsharpclient.sln --include-symbols -p:SymbolPackageFormat=snupkg --configuration $env:configuration -o ((get-location).Path + '\artifacts') /property:Version=$fileVersion 
    
artifacts:
- path: artifacts\**\*.*

cache:
- '%USERPROFILE%\.nuget\packages'
  
nuget:
  disable_publish_on_pr: true
#  account_feed: true
#  project_feed: true
  
deploy:
- provider: NuGet
  api_key:
    secure: NK6JEky2i7+06Ij+PlJX7X0xlKT4fg2zDIFP5fiFSy6EqxcIYThFBkzzqpQTUnsO
